# Generated by Django 5.0.6 on 2024-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('catagory', models.ManyToManyField(to='catagory.catagory')),
            ],
        ),
    ]
